coverage_service: cobertura_xml
output_directory: ./
source_directory:
  - Domain
  - Presentation
  - Infrastructure
binary_basename:
  - Domain
  - Presentation
  - Infrastructure

workspace: Parking.xcworkspace
scheme: Presentation
xcodeproj: Presentation/Presentation.xcodeproj