coverage_service: cobertura_xml
output_directory: ./
source_directory:
  - Domain
binary_basename:
  - Domain
  - Presentation
ignore:
  - Infrastructure
  - Presentation

workspace: Parking.xcworkspace
scheme: Domain
xcodeproj: Presentation/Presentation.xcodeproj